-- Supabase/PostgreSQL-compatible adaptation of database_update_comprehensive.sql
-- Original schema intent and data operations are preserved; MySQL-only clauses were translated or neutralized.

-- Comprehensive Database Update Script for Kids E-commerce Platform
-- This script updates the database schema to match the Flask models

-- Disable foreign key checks temporarily
-- Update User table to match model
ALTER TABLE "user" 
ADD COLUMN IF NOT EXISTS "username" varchar(30) NOT NULL DEFAULT 'user',
-- MODIFY COLUMN "first_name" varchar(80) NOT NULL,
-- MODIFY COLUMN "last_name" varchar(80) NOT NULL,
-- MODIFY COLUMN "email" varchar(120) NOT NULL,
-- MODIFY COLUMN "password" varchar(120) NOT NULL,
-- MODIFY COLUMN "phone" varchar(20) NOT NULL,
-- MODIFY COLUMN "address" text NOT NULL,
-- MODIFY COLUMN "role" varchar(20) DEFAULT 'buyer',
-- MODIFY COLUMN "status" varchar(20) DEFAULT 'active',
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "two_factor_enabled" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "email_notifications" boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS "email_verified" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "verification_code" varchar(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "valid_id" varchar(255) DEFAULT NULL;

-- Add indexes for User table
CREATE INDEX IF NOT EXISTS "idx_user_email" ON "user" ("email");CREATE INDEX IF NOT EXISTS "idx_user_username" ON "user" ("username");CREATE INDEX IF NOT EXISTS "idx_user_status" ON "user" ("status");

-- Update SellerApplication table
ALTER TABLE "seller_application" 
ADD COLUMN IF NOT EXISTS "store_description" text,
ADD COLUMN IF NOT EXISTS "store_category" varchar(100) NOT NULL DEFAULT 'General',
-- MODIFY COLUMN "applied_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "store_logo" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "store_mission" text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "return_policy" text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "return_days" integer DEFAULT 7,
ADD COLUMN IF NOT EXISTS "refund_method" varchar(50) DEFAULT 'Original Payment Method',
ADD COLUMN IF NOT EXISTS "business_registration" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "valid_id" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "store_banner" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "followers_count" integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS "store_rating" double precision DEFAULT 5,
ADD COLUMN IF NOT EXISTS "chat_enabled" boolean DEFAULT true;

-- Update Order table
ALTER TABLE "order"
-- MODIFY COLUMN "total_amount" decimal(10,2) NOT NULL,
-- MODIFY COLUMN "status" varchar(20) DEFAULT 'pending',
-- MODIFY COLUMN "payment_method" varchar(50) NOT NULL,
-- MODIFY COLUMN "payment_status" varchar(20) DEFAULT 'pending',
-- MODIFY COLUMN "shipping_address" text NOT NULL,
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp(),
-- MODIFY COLUMN "updated_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "stock_deducted" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "stock_deducted_at" timestamp NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "qr_code" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "tracking_number" varchar(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "batch_code" varchar(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "label_generated_at" timestamp NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "packed_at" timestamp NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "picked_up_at" timestamp NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "delivered_at" timestamp NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "packed_by" integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "picked_up_by" integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "delivered_by" integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "shipping_notes" text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "delivery_notes" text DEFAULT NULL;

-- Add foreign key constraints for Order table
ALTER TABLE "order" 
ADD CONSTRAINT "order_packed_by_fk" FOREIGN KEY ("packed_by") REFERENCES "user" ("id"),
ADD CONSTRAINT "order_picked_up_by_fk" FOREIGN KEY ("picked_up_by") REFERENCES "user" ("id"),
ADD CONSTRAINT "order_delivered_by_fk" FOREIGN KEY ("delivered_by") REFERENCES "user" ("id");

-- Update OrderItem table
-- ALTER TABLE "order_item" (no-op: MySQL MODIFY COLUMN statements omitted)
-- MODIFY COLUMN "quantity" integer NOT NULL,
-- MODIFY COLUMN "price_at_time" decimal(10,2) NOT NULL;

-- Update Cart table
-- ALTER TABLE "cart" (no-op: MySQL MODIFY COLUMN statements omitted)
-- MODIFY COLUMN "quantity" integer NOT NULL DEFAULT 1,
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp();

-- Create missing tables if they don't exist

-- SellerOrderSeen table
CREATE TABLE IF NOT EXISTS "seller_order_seen" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "seller_id" integer NOT NULL,
  "order_id" integer NOT NULL,
  "seen_at" timestamp DEFAULT current_timestamp(),
  PRIMARY KEY ("id"),
  -- KEY "idx_seller_order_seen_seller" ("seller_id")
  -- KEY "idx_seller_order_seen_order" ("order_id")
  CONSTRAINT "seller_order_seen_seller_fk" FOREIGN KEY ("seller_id") REFERENCES "user" ("id"),
  CONSTRAINT "seller_order_seen_order_fk" FOREIGN KEY ("order_id") REFERENCES "order" ("id")
);

-- ReturnRequest table
CREATE TABLE IF NOT EXISTS "return_request" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "order_id" integer NOT NULL,
  "order_item_id" integer NOT NULL,
  "buyer_id" integer NOT NULL,
  "seller_id" integer NOT NULL,
  "reason" text NOT NULL,
  "reason_other" text DEFAULT NULL,
  "description" text DEFAULT NULL,
  "quantity" integer DEFAULT 1,
  "images" json DEFAULT NULL,
  "video_filename" varchar(255) DEFAULT NULL,
  "request_type" varchar(20) NOT NULL,
  "status" varchar(30) DEFAULT 'submitted',
  "created_at" timestamp DEFAULT current_timestamp(),
  "processed_at" timestamp DEFAULT NULL,
  "processed_by" integer DEFAULT NULL,
  "refund_amount" decimal(10,2) DEFAULT NULL,
  "admin_notes" text DEFAULT NULL,
  "updated_at" timestamp DEFAULT current_timestamp(),
  "seller_response_reason" text DEFAULT NULL,
  PRIMARY KEY ("id"),
  -- KEY "return_request_order_fk" ("order_id")
  -- KEY "return_request_order_item_fk" ("order_item_id")
  -- KEY "return_request_buyer_fk" ("buyer_id")
  -- KEY "return_request_seller_fk" ("seller_id")
  CONSTRAINT "return_request_order_fk" FOREIGN KEY ("order_id") REFERENCES "order" ("id"),
  CONSTRAINT "return_request_order_item_fk" FOREIGN KEY ("order_item_id") REFERENCES "order_item" ("id"),
  CONSTRAINT "return_request_buyer_fk" FOREIGN KEY ("buyer_id") REFERENCES "user" ("id"),
  CONSTRAINT "return_request_seller_fk" FOREIGN KEY ("seller_id") REFERENCES "user" ("id"),
  CONSTRAINT "return_request_processed_by_fk" FOREIGN KEY ("processed_by") REFERENCES "user" ("id")
);

-- RestockRequest table
CREATE TABLE IF NOT EXISTS "restock_request" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "seller_id" integer NOT NULL,
  "requested_quantity" integer NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "created_at" timestamp DEFAULT current_timestamp(),
  "processed_at" timestamp DEFAULT NULL,
  "processed_by" integer DEFAULT NULL,
  "admin_notes" text DEFAULT NULL,
  "approved_quantity" integer DEFAULT NULL,
  PRIMARY KEY ("id"),
  -- KEY "restock_request_product_fk" ("product_id")
  -- KEY "restock_request_seller_fk" ("seller_id")
  -- KEY "restock_request_processed_by_fk" ("processed_by")
  CONSTRAINT "restock_request_product_fk" FOREIGN KEY ("product_id") REFERENCES "product" ("id"),
  CONSTRAINT "restock_request_seller_fk" FOREIGN KEY ("seller_id") REFERENCES "user" ("id"),
  CONSTRAINT "restock_request_processed_by_fk" FOREIGN KEY ("processed_by") REFERENCES "user" ("id")
);

-- ReturnPickup table
CREATE TABLE IF NOT EXISTS "return_pickup" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "return_request_id" integer NOT NULL,
  "rider_id" integer DEFAULT NULL,
  "status" varchar(30) DEFAULT 'available',
  "buyer_address" text DEFAULT NULL,
  "seller_address" text DEFAULT NULL,
  "created_at" timestamp DEFAULT current_timestamp(),
  "updated_at" timestamp DEFAULT current_timestamp(),
  "picked_up_at" timestamp DEFAULT NULL,
  "delivered_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id"),
  -- KEY "return_pickup_return_request_fk" ("return_request_id")
  -- KEY "return_pickup_rider_fk" ("rider_id")
  CONSTRAINT "return_pickup_return_request_fk" FOREIGN KEY ("return_request_id") REFERENCES "return_request" ("id"),
  CONSTRAINT "return_pickup_rider_fk" FOREIGN KEY ("rider_id") REFERENCES "user" ("id")
);

-- WalletTransaction table
CREATE TABLE IF NOT EXISTS "wallet_transaction" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "order_id" integer DEFAULT NULL,
  "amount" decimal(10,2) NOT NULL,
  "type" varchar(20) DEFAULT 'credit',
  "source" varchar(50) DEFAULT NULL,
  "created_at" timestamp DEFAULT current_timestamp(),
  PRIMARY KEY ("id"),
  -- KEY "wallet_transaction_user_fk" ("user_id")
  -- KEY "wallet_transaction_order_fk" ("order_id")
  CONSTRAINT "wallet_transaction_user_fk" FOREIGN KEY ("user_id") REFERENCES "user" ("id"),
  CONSTRAINT "wallet_transaction_order_fk" FOREIGN KEY ("order_id") REFERENCES "order" ("id")
);

-- RiderChatMessage table
CREATE TABLE IF NOT EXISTS "rider_chat_message" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "buyer_id" integer NOT NULL,
  "rider_id" integer NOT NULL,
  "order_id" integer DEFAULT NULL,
  "message" text NOT NULL,
  "sender_role" varchar(10) NOT NULL,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT current_timestamp(),
  PRIMARY KEY ("id"),
  -- KEY "rider_chat_buyer_fk" ("buyer_id")
  -- KEY "rider_chat_rider_fk" ("rider_id")
  -- KEY "rider_chat_order_fk" ("order_id")
  CONSTRAINT "rider_chat_buyer_fk" FOREIGN KEY ("buyer_id") REFERENCES "user" ("id"),
  CONSTRAINT "rider_chat_rider_fk" FOREIGN KEY ("rider_id") REFERENCES "user" ("id"),
  CONSTRAINT "rider_chat_order_fk" FOREIGN KEY ("order_id") REFERENCES "order" ("id")
);

-- Coupon table
CREATE TABLE IF NOT EXISTS "coupon" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "code" varchar(50) NOT NULL,
  "description" varchar(255) DEFAULT NULL,
  "discount_type" varchar(20) DEFAULT 'percent',
  "discount_value" decimal(10,2) NOT NULL,
  "min_order_amount" decimal(10,2) DEFAULT 0.00,
  "max_uses" integer DEFAULT NULL,
  "used_count" integer DEFAULT 0,
  "valid_from" timestamp DEFAULT NULL,
  "valid_until" timestamp DEFAULT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT current_timestamp(),
  PRIMARY KEY ("id"),
  CONSTRAINT "coupon_code_unique" UNIQUE ("code")
);

-- RiderApplication table
CREATE TABLE IF NOT EXISTS "rider_application" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "vehicle_type" varchar(50) NOT NULL,
  "vehicle_number" varchar(20) NOT NULL,
  "employee_id" varchar(50) DEFAULT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "applied_at" timestamp DEFAULT current_timestamp(),
  "reviewed_at" timestamp DEFAULT NULL,
  "reviewed_by" integer DEFAULT NULL,
  PRIMARY KEY ("id"),
  -- KEY "rider_application_user_fk" ("user_id")
  -- KEY "rider_application_reviewed_by_fk" ("reviewed_by")
  CONSTRAINT "rider_application_user_fk" FOREIGN KEY ("user_id") REFERENCES "user" ("id"),
  CONSTRAINT "rider_application_reviewed_by_fk" FOREIGN KEY ("reviewed_by") REFERENCES "user" ("id")
);

-- Update Product table
ALTER TABLE "product"
-- MODIFY COLUMN "name" varchar(120) NOT NULL,
-- MODIFY COLUMN "description" text NOT NULL,
-- MODIFY COLUMN "price" decimal(10,2) NOT NULL,
-- MODIFY COLUMN "stock" integer NOT NULL DEFAULT 0,
-- MODIFY COLUMN "status" varchar(20) DEFAULT 'active',
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "video_filename" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "gallery" json DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "subcategory_id" integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "is_deleted" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "rejection_reason" text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "featured" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "show_in_new_arrival" boolean NOT NULL DEFAULT false;

-- Add foreign key for product subcategory
ALTER TABLE "product" 
ADD CONSTRAINT "product_subcategory_fk" FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id");

-- Update Review table
ALTER TABLE "review"
-- MODIFY COLUMN "rating" integer NOT NULL,
-- MODIFY COLUMN "created_at" timestamp DEFAULT current_timestamp(),
-- MODIFY COLUMN "status" varchar(20) DEFAULT 'published',
ADD COLUMN IF NOT EXISTS "media" json DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "verified_purchase" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "order_id" integer DEFAULT NULL;

-- Add foreign key for review order
ALTER TABLE "review" 
ADD CONSTRAINT "review_order_fk" FOREIGN KEY ("order_id") REFERENCES "order" ("id");

-- Update Notification table
ALTER TABLE "notification"
-- MODIFY COLUMN "created_at" timestamp DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "image_url" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "link" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "type" varchar(40) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "actor_user_id" integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "order_id" integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "images" json DEFAULT NULL;

-- Add foreign keys for notification
ALTER TABLE "notification" 
ADD CONSTRAINT "notification_actor_fk" FOREIGN KEY ("actor_user_id") REFERENCES "user" ("id");

-- Update Address table
ALTER TABLE "address"
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "latitude" double precision DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "longitude" double precision DEFAULT NULL;

-- Update Category table
ALTER TABLE "category"
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "cover_image_filename" varchar(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "status" varchar(20) DEFAULT 'active';

-- Update Subcategory table
ALTER TABLE "subcategory"
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "status" varchar(20) DEFAULT 'active';

-- Update HeroSlide table
-- ALTER TABLE "hero_slide" (no-op: MySQL MODIFY COLUMN statements omitted)
-- MODIFY COLUMN "created_at" timestamp DEFAULT current_timestamp(),
-- MODIFY COLUMN "is_active" boolean DEFAULT true;

-- Update ThemeSetting table
-- ALTER TABLE "theme_setting" (no-op: MySQL MODIFY COLUMN statements omitted)
-- MODIFY COLUMN "slide_duration" double precision precision DEFAULT 6,
-- MODIFY COLUMN "transition_duration" double precision precision DEFAULT 0.8;

-- Update DeliveryPersonnel table
-- ALTER TABLE "delivery_personnel" (no-op: MySQL MODIFY COLUMN statements omitted)
-- MODIFY COLUMN "created_at" timestamp DEFAULT NULL,
-- MODIFY COLUMN "updated_at" timestamp DEFAULT NULL,
-- MODIFY COLUMN "status" varchar(20) DEFAULT NULL;

-- Update QRScanLog table
-- ALTER TABLE "qr_scan_log" (no-op: MySQL MODIFY COLUMN statements omitted)
-- MODIFY COLUMN "created_at" timestamp DEFAULT NULL;

-- Update OrderLabel table
ALTER TABLE "order_label"
-- MODIFY COLUMN "created_at" timestamp DEFAULT NULL,
-- MODIFY COLUMN "updated_at" timestamp DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "returned_by" integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "return_notes" text DEFAULT NULL;

-- Add foreign key for order_label returned_by
ALTER TABLE "order_label" 
ADD CONSTRAINT "order_label_returned_by_fk" FOREIGN KEY ("returned_by") REFERENCES "user" ("id");

-- Update StoreChatMessage table
ALTER TABLE "store_chat_message"
-- MODIFY COLUMN "created_at" timestamp DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "is_read" boolean DEFAULT NULL;

-- Drop and recreate Flask Dance OAuth table if needed
DROP TABLE IF EXISTS "flask_dance_oauth";

-- Update OAuth table
ALTER TABLE "oauth"
-- MODIFY COLUMN "created_at" timestamp NOT NULL DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS "provider_user_id" varchar(256) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "provider" varchar(50) DEFAULT NULL;

-- Fix OAuth table structure
ALTER TABLE "oauth" 
-- MODIFY COLUMN "provider_user_id" varchar(256) NOT NULL,
-- MODIFY COLUMN "provider" varchar(50) NOT NULL,
DROP CONSTRAINT IF EXISTS "provider_user_id",
ADD CONSTRAINT "provider_user_id" UNIQUE ("provider_user_id");

-- Re-enable foreign key checks
-- Insert missing default data

-- Insert default theme setting if not exists
INSERT INTO "theme_setting" ("id", "logo_filename", "site_name", "primary_color", "secondary_color", "footer_color", "slide_duration", "transition_duration") 
VALUES (1, 'logo_ulit.png', 'Kids & Baby Store', '#1a2842', '#000000', '#1a2842', 6, 0.8);

-- Insert default admin user if not exists
INSERT INTO "user" ("id", "username", "first_name", "last_name", "email", "password", "phone", "address", "role", "status", "email_verified", "verification_code", "valid_id", "created_at", "two_factor_enabled", "email_notifications") 
VALUES (1, 'admin', 'Admin', 'User', 'admin@kidscommerce.com', 'admin123', '09123456789', 'Admin Office, Manila', 'admin', 'active', false, NULL, NULL, NOW(), false, true);

-- Insert admin profile if not exists
INSERT INTO "admin_profile" ("id", "user_id", "full_name", "contact_number", "system_role", "last_login", "account_status", "two_factor_enabled", "password_reset_required", "created_at", "updated_at") 
VALUES (1, 1, 'Admin User', '09123456789', 'Administrator', NULL, 'Active', false, false, NOW(), NOW());

-- Update existing users to have usernames if missing
UPDATE "user" SET "username" = CONCAT('user', "id") WHERE "username" = 'user' OR "username" IS NULL;

-- Update existing products to have proper defaults
UPDATE "product" SET "featured" = false WHERE "featured" IS NULL;UPDATE "product" SET "show_in_new_arrival" = false WHERE "show_in_new_arrival" IS NULL;UPDATE "product" SET "is_deleted" = false WHERE "is_deleted" IS NULL;

-- Update existing addresses to have proper defaults
UPDATE "address" SET "latitude" = NULL WHERE "latitude" IS NULL;UPDATE "address" SET "longitude" = NULL WHERE "longitude" IS NULL;

-- Update existing notifications to have proper defaults
UPDATE "notification" SET "is_read" = false WHERE "is_read" IS NULL;

-- Update existing store chat messages to have proper defaults
UPDATE "store_chat_message" SET "is_read" = false WHERE "is_read" IS NULL;

-- Update existing reviews to have proper defaults
UPDATE "review" SET "verified_purchase" = false WHERE "verified_purchase" IS NULL;

-- Commit the changes
COMMIT;
